@host_Local = https://localhost:44314
@host_Local_NetCore = https://localhost:5001
@hostname = {{host_Local}}

###

GET {{hostname}}/api/Values/Test HTTP/1.1

###

GET {{hostname}}/api/Some/AsyncGet HTTP/1.1

###

GET {{hostname}}/api/Some/Get HTTP/1.1
